// <auto-generated />
using System;
using LimonikOne.Modules.Product.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LimonikOne.Modules.Product.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20260315120000_RenameProductsTableToItems")]
    partial class RenameProductsTableToItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("product")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LimonikOne.Modules.Product.Domain.Items.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Certification")
                        .HasColumnType("integer")
                        .HasColumnName("certification");

                    b.Property<long>("DisplayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("display_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("DisplayId"));

                    b.Property<int>("Handling")
                        .HasColumnType("integer")
                        .HasColumnName("handling");

                    b.Property<string>("ItemNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("item_number");

                    b.Property<string>("PrimaryName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("primary_name");

                    b.Property<string>("SearchName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("search_name");

                    b.Property<int>("Stage")
                        .HasColumnType("integer")
                        .HasColumnName("stage");

                    b.Property<int>("Variety")
                        .HasColumnType("integer")
                        .HasColumnName("variety");

                    b.HasKey("Id");

                    b.HasIndex("DisplayId")
                        .IsUnique();

                    b.HasIndex("ItemNumber")
                        .IsUnique();

                    b.HasIndex("SearchName");

                    b.ToTable("items", "product");
                });
#pragma warning restore 612, 618
        }
    }
}
