// <auto-generated />
using System;
using LimonikOne.Modules.Scale.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LimonikOne.Modules.Scale.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ScaleDbContext))]
    [Migration("20260310164402_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("scale")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LimonikOne.Modules.Scale.Domain.Weights.WeightBatchEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_id");

                    b.Property<long>("DisplayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("display_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("DisplayId"));

                    b.Property<Guid>("ExternalBatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_batch_id");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.HasKey("Id");

                    b.HasIndex("DisplayId")
                        .IsUnique();

                    b.HasIndex("ExternalBatchId")
                        .IsUnique();

                    b.ToTable("weight_batches", "scale");
                });

            modelBuilder.Entity("LimonikOne.Modules.Scale.Domain.Weights.WeightBatchEntity", b =>
                {
                    b.OwnsMany("LimonikOne.Modules.Scale.Domain.Weights.WeightReading", "Readings", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("Count")
                                .HasColumnType("integer")
                                .HasColumnName("count");

                            b1.Property<DateTime>("FirstTimestamp")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("first_timestamp");

                            b1.Property<DateTime>("LastTimestamp")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("last_timestamp");

                            b1.Property<int>("StableCount")
                                .HasColumnType("integer")
                                .HasColumnName("stable_count");

                            b1.Property<decimal>("Weight")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("weight");

                            b1.Property<Guid>("weight_batch_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("weight_batch_id");

                            b1.ToTable("weight_readings", "scale");

                            b1.WithOwner()
                                .HasForeignKey("weight_batch_id");
                        });

                    b.Navigation("Readings");
                });
#pragma warning restore 612, 618
        }
    }
}
