// <auto-generated />
using System;
using LimonikOne.Modules.Scale.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LimonikOne.Modules.Scale.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ScaleDbContext))]
    [Migration("20260313182912_SplitWeightReadingAsAggregate")]
    partial class SplitWeightReadingAsAggregate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("scale")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LimonikOne.Modules.Scale.Domain.WeighingEvents.WeighingEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_id");

                    b.Property<long>("DisplayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("display_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("DisplayId"));

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<decimal>("PeakWeight")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("peak_weight");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("DisplayId")
                        .IsUnique();

                    b.HasIndex("DeviceId", "Status");

                    b.ToTable("weighing_events", "scale");
                });

            modelBuilder.Entity("LimonikOne.Modules.Scale.Domain.Weights.WeightBatchEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_id");

                    b.Property<long>("DisplayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("display_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("DisplayId"));

                    b.Property<Guid>("ExternalBatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_batch_id");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.HasKey("Id");

                    b.HasIndex("DisplayId")
                        .IsUnique();

                    b.HasIndex("ExternalBatchId")
                        .IsUnique();

                    b.ToTable("weight_batches", "scale");
                });

            modelBuilder.Entity("LimonikOne.Modules.Scale.Domain.Weights.WeightReading", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("weight_batch_id");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.Property<long>("DisplayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("display_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("DisplayId"));

                    b.Property<DateTime>("FirstTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_timestamp");

                    b.Property<DateTime>("LastTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_timestamp");

                    b.Property<int>("StableCount")
                        .HasColumnType("integer")
                        .HasColumnName("stable_count");

                    b.Property<decimal>("Weight")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("DisplayId")
                        .IsUnique();

                    b.ToTable("weight_readings", "scale");
                });

            modelBuilder.Entity("LimonikOne.Modules.Scale.Domain.WeighingEvents.WeighingEventEntity", b =>
                {
                    b.OwnsMany("LimonikOne.Modules.Scale.Domain.WeighingEvents.WeighingMeasurement", "Measurements", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("SourceReadingId")
                                .HasColumnType("uuid")
                                .HasColumnName("source_reading_id");

                            b1.Property<int>("StableCount")
                                .HasColumnType("integer")
                                .HasColumnName("stable_count");

                            b1.Property<DateTime>("Timestamp")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("timestamp");

                            b1.Property<decimal>("Weight")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("weight");

                            b1.Property<Guid>("weighing_event_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("weighing_event_id");

                            b1.ToTable("weighing_measurements", "scale");

                            b1.WithOwner()
                                .HasForeignKey("weighing_event_id");
                        });

                    b.Navigation("Measurements");
                });

            modelBuilder.Entity("LimonikOne.Modules.Scale.Domain.Weights.WeightReading", b =>
                {
                    b.HasOne("LimonikOne.Modules.Scale.Domain.Weights.WeightBatchEntity", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
